-- Auth user and seller provisioning is handled by scripts/provision-ci-admin.ts
-- which uses the Supabase Auth Admin API to create a login-capable user and
-- links a sellers row at runtime. Do not insert auth.users rows or seller
-- credentials here.
